server:
  port: 8080
spring:
  servlet:
    multipart:
      location: F:/test
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    lettuce:
      pool:
        max-active: 100
        max-wait: PT10S
        max-idle: 30
        min-idle: 1
    timeout: PT10S
    host: 192.168.1.120
    port: 6379

  messages:
    encoding: utf-8
    basename: international
    cache-duration: 3600
  datasource:
    url: jdbc:mysql://192.168.1.120:3307/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.huawei.springboot.domain