server:
  port: 8080
spring:
  servlet:
    multipart:
      location: F:/test
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    lettuce:
      pool:
        max-active: 100
        max-wait: PT10S
        max-idle: 30
        min-idle: 1
    timeout: PT10S
    host: 192.168.1.120
    port: 6380

  messages:
    encoding: utf-8
    basename: international
    cache-duration: 3600
  datasource:
    druid:
      min-idle: 5
      max-active: 20
      max-wait: 10000
      initial-size: 5
      url: jdbc:mysql://192.168.1.120:3307/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.huawei.springboot.domain